const actionType = {
    GET_HOME: 'GET_HOME',
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_ARTICLES: 'GET_ARTICLES',
    GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
    GET_ARTICLE_DETAIL: 'GET_ARTICLE_DETAIL',
}

export default actionType