const actionType = {
    GET_HOME: 'GET_HOME',
    GET_PRODUCTS: 'GET_PRODUCTS',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_CURRENT_PAGE_ARTICLE: 'SET_CURRENT_PAGE_ARTICLE',
    GET_ARTICLES: 'GET_ARTICLES',
    GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
    GET_ARTICLE_DETAIL: 'GET_ARTICLE_DETAIL',
}

export default actionType