const actionType = {
    REGISTER: 'REGISTER',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN: "LOGIN",
    LOGIN_FAIL: "LOGIN_FAIL",
    GET_HOME: 'GET_HOME',
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_ARTICLES: 'GET_ARTICLES',
    GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
    GET_ARTICLE_DETAIL: 'GET_ARTICLE_DETAIL',
    GET_VIDEO_DETAIL: 'GET_VIDEO_DETAIL',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
}

export default actionType